services:
  # The "Brain" - Collects all data
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8889:8889"

  # Metrics Storage
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Log Storage
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/tmp/loki  
    command: -config.file=/etc/loki/local-config.yaml

  # Visualization & AI UI
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph,traceqlEditor,autoNamespacing

  sample-app:
    image: grafana/k6:latest
    # We map the scripts folder so k6 can find your load-test.js
    volumes:
      - ./scripts:/scripts
    command: run /scripts/load-test.js
    depends_on:
      - otel-collector

  # Trace Storage
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200"   # Tempo UI/API
      - "4317:4317"        # OTLP gRPC (internal)
